[package]
name = "sqlx-txn-repro"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
anyhow = "1"
crdb-harness = "0.0.1"
futures = "0.3"
sqlx = { version = "0.8.2", features = ["postgres", "runtime-tokio"]}
tokio = { version = "1.40.0", features = ["full"] }
